package github

import (
	"context"
	"fmt"
	"strings"

	gogithub "github.com/google/go-github/v60/github"
)

// maxDiffBytes caps the diff sent to the model to keep latency and token usage
// bounded on very large Pull Requests.
const maxDiffBytes = 60000

// skipExtensions and skipFilenames list the file suffixes and names excluded
// from the diff to reduce noise and token consumption (locks, assets,
// generated/binary files).
var (
	skipExtensions = []string{
		".lock", ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico",
		".pdf", ".zip", ".gz", ".tar", ".mp4", ".mp3", ".woff",
		".woff2", ".ttf", ".eot", ".min.js", ".min.css",
	}
	skipFilenames = []string{
		"package-lock.json", "yarn.lock", "pnpm-lock.yaml",
		"go.sum", "composer.lock", "Cargo.lock", "poetry.lock",
	}
)

// NewClient returns a GitHub API client authenticated with token.
func NewClient(token string) *gogithub.Client {
	return gogithub.NewClient(nil).WithAuthToken(token)
}

// BuildDiff fetches the changed files of pr and assembles a filtered unified
// diff string, skipping binary/asset/lock files and truncating if oversized.
func BuildDiff(ctx context.Context, client *gogithub.Client, pr PullRequest) (string, error) {
	var builder strings.Builder
	opts := &gogithub.ListOptions{PerPage: 100}

	for {
		files, resp, err := client.PullRequests.ListFiles(ctx, pr.Owner, pr.Repo, pr.Number, opts)
		if err != nil {
			return "", fmt.Errorf("listing PR files: %w", err)
		}

		for _, f := range files {
			filename := f.GetFilename()
			if shouldSkip(filename) {
				continue
			}
			patch := f.GetPatch()
			if patch == "" {
				continue
			}

			fmt.Fprintf(&builder, "### File: %s (+%d/-%d)\n", filename, f.GetAdditions(), f.GetDeletions())
			builder.WriteString("```diff\n")
			builder.WriteString(patch)
			builder.WriteString("\n```\n\n")

			if builder.Len() >= maxDiffBytes {
				builder.WriteString("\n[diff truncated due to size limit]\n")
				return builder.String(), nil
			}
		}

		if resp.NextPage == 0 {
			break
		}
		opts.Page = resp.NextPage
	}

	return builder.String(), nil
}

// PostComment publishes review as an issue comment on pr. model is used only in
// the attribution footer.
func PostComment(ctx context.Context, client *gogithub.Client, pr PullRequest, review, model string) error {
	body := "## Claude Code Review\n\n" + review +
		"\n\n---\n<sub>Generated by [claude-pr-reviewer](https://github.com/vparlici/claude-pr-reviewer) using `" + model + "`.</sub>"

	comment := &gogithub.IssueComment{Body: gogithub.String(body)}
	if _, _, err := client.Issues.CreateComment(ctx, pr.Owner, pr.Repo, pr.Number, comment); err != nil {
		return fmt.Errorf("creating issue comment: %w", err)
	}
	return nil
}

// shouldSkip reports whether a file should be excluded from the review diff.
func shouldSkip(filename string) bool {
	lower := strings.ToLower(filename)
	base := lower
	if idx := strings.LastIndexAny(lower, "/\\"); idx >= 0 {
		base = lower[idx+1:]
	}

	for _, name := range skipFilenames {
		if base == strings.ToLower(name) {
			return true
		}
	}
	for _, ext := range skipExtensions {
		if strings.HasSuffix(lower, ext) {
			return true
		}
	}
	return false
}
